name: publish
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare dependencies
        run: npm update
      - name: Install
        run: npm install
      - name: Build
      - run: npm run build
      - name: Fix permissions
          run: |
            chmod -c -R +rX "public/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "public"
          name: "resume"
